blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://minikube.sigs.k8s.io/docs/
    about: Please check the documentation before opening an issue.
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/minikube
    about: Ask questions about minikube usage on Stack Overflow.
  - name: Slack
    url: https://kubernetes.slack.com/messages/minikube
    about: Chat with the minikube community on Slack.
