name: Reporte de Error (Español)
description: Reportar un error para ayudarnos a mejorar
title: "[Bug] "
labels: ["kind/bug", "language/es"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarse el tiempo para rellenar este informe de error. Por favor, proporcione tanta información como sea posible.
  - type: textarea
    id: description
    attributes:
      label: Descripción del error
      description: Una descripción clara y concisa de cuál es el error.
      placeholder: Describe el error aquí...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Pasos para reproducir
      description: Pasos para reproducir el comportamiento.
      placeholder: |
        1. Ejecutar '...'
        2. Ver el error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Una descripción clara y concisa de lo que esperabas que sucediera.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamiento actual
      description: Una descripción clara y concisa de lo que está sucediendo actualmente.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Versión de minikube
      description: Ejecuta `minikube version` y pega el resultado aquí.
      placeholder: minikube version
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Entorno
      description: |
        Ejecuta `minikube logs` y pega el resultado aquí.
        También incluye información sobre tu sistema operativo, arquitectura y controlador.
      placeholder: |
        - SO: [ej. Ubuntu 22.04, macOS 13, Windows 11]
        - Arquitectura: [ej. amd64, arm64]
        - Controlador: [ej. docker, virtualbox, kvm2]
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Registros de salida
      description: Por favor, copia y pega cualquier salida de registro relevante.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conducta
      description: Al enviar este problema, aceptas seguir nuestro [Código de Conducta](https://github.com/kubernetes/minikube/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: Acepto seguir el Código de Conducta de este proyecto
          required: true
